# Generated by Django 5.2.5 on 2025-08-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pointadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='photo',
            field=models.ImageField(blank=True, help_text='Nuotrauka (jei nenaudojamas emoji)', null=True, upload_to='kid_avatars/'),
        ),
    ]
