# Generated by Django 5.2.5 on 2025-08-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_kid_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='icon_emoji',
            field=models.CharField(blank=True, default='', help_text='Emoji (pvz. 🧹) – jei nėra paveikslėlio', max_length=8),
        ),
        migrations.AddField(
            model_name='chore',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Paveikslėlis (128x128 rekomenduojama)', null=True, upload_to='chore_icons/'),
        ),
        migrations.AddField(
            model_name='reward',
            name='icon_emoji',
            field=models.CharField(blank=True, default='', help_text='Emoji (pvz. 🎁) – jei nėra paveikslėlio', max_length=8),
        ),
        migrations.AddField(
            model_name='reward',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Paveikslėlis (128x128 rekomenduojama)', null=True, upload_to='reward_icons/'),
        ),
        migrations.AlterField(
            model_name='kid',
            name='avatar_emoji',
            field=models.CharField(blank=True, default='', help_text='Emoji (jei tuščia – generuojama raidė)', max_length=4),
        ),
    ]
