# Generated by Django 5.2.5 on 2025-10-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_chore_icon_emoji_chore_icon_image_reward_icon_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='map_position',
            field=models.IntegerField(default=0, help_text='Nuotykių žemėlapio pozicija (suskaičiuoti taškai)'),
        ),
    ]
