# Generated by Django 5.2.5 on 2025-10-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_kid_map_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='map_theme',
            field=models.CharField(choices=[('ISLAND', 'Island'), ('SPACE', 'Space'), ('RAINBOW', 'Rainbow Road')], default='ISLAND', help_text='Nuotykių žemėlapio tema', max_length=10),
        ),
    ]
