# Generated by Django 5.2.5 on 2025-10-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_kid_map_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='highest_milestone',
            field=models.IntegerField(default=0, help_text='Aukščiausias pasiektas milestone pozicija'),
        ),
    ]
