# Generated by Django 5.2.5 on 2025-10-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_milestone_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointadjustment',
            name='points',
            field=models.IntegerField(help_text='Teigiamas skaičius prideda taškus, neigiamas - atima'),
        ),
        migrations.AlterField(
            model_name='pointadjustment',
            name='reason',
            field=models.CharField(help_text='Priežastis (matoma vaikui)', max_length=255),
        ),
    ]
