# Generated by Django 5.2.7 on 2025-10-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_initial_chores_rewards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chore',
            options={'verbose_name': 'Darbas', 'verbose_name_plural': 'Darbai'},
        ),
        migrations.AlterModelOptions(
            name='chorelog',
            options={'verbose_name': 'Darbo įrašas', 'verbose_name_plural': 'Darbų įrašai'},
        ),
        migrations.AlterModelOptions(
            name='kid',
            options={'verbose_name': 'Vaikas', 'verbose_name_plural': 'Vaikai'},
        ),
        migrations.AlterModelOptions(
            name='pointadjustment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Taškų koregavimas', 'verbose_name_plural': 'Taškų koregavimai'},
        ),
        migrations.AlterModelOptions(
            name='redemption',
            options={'verbose_name': 'Apdovanojimo išpirkimas', 'verbose_name_plural': 'Apdovanojimų išpirkimai'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'Apdovanojimas', 'verbose_name_plural': 'Apdovanojimai'},
        ),
        migrations.AddField(
            model_name='kid',
            name='gender',
            field=models.CharField(choices=[('M', 'Berniukas'), ('F', 'Mergaitė'), ('O', 'Kita')], default='M', help_text='Lytis (sveikinimuiui)', max_length=1),
        ),
        migrations.AlterField(
            model_name='chorelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Laukia'), ('APPROVED', 'Patvirtinta'), ('REJECTED', 'Atmesta')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='kid',
            name='map_theme',
            field=models.CharField(choices=[('ISLAND', 'Sala'), ('SPACE', 'Kosmosas'), ('RAINBOW', 'Vaivorykštės kelias')], default='ISLAND', help_text='Nuotykių žemėlapio tema', max_length=10),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Laukia'), ('APPROVED', 'Patvirtinta'), ('REJECTED', 'Atmesta')], default='PENDING', max_length=10),
        ),
    ]
